CREATE DATABASE IF NOT EXISTS website;

USE website;

CREATE TABLE IF NOT EXISTS google_users(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    google_id DECIMAL(21,0) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL
);